spring:
  datasource:
    name: datasource
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${database.driver}
    filters: stat
    maxActive: ${database.maxActive}
    initialSize: ${database.initialSize}
    maxWait: 60000
    minIdle: ${database.minIdle}
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select '1' as txt
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/com/emrubik/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.baomidou.mybatisplus.test.h2.entity
  type-handlers-package: ${mybatis.typehandler.package:com.emrubik.oak.dao.mybatis.handler}
  global-config:
    #自定义填充策略接口实现
    meta-object-handler: MyMetaObjectHandler
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #驼峰下划线转换
    db-column-underline: true
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #自定义SQL注入器
    sql-injector: com.emrubik.oak.dao.mybatisplus.ExtLogicSqlInjector
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: true
    logic-not-delete-value: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: SIMPLE
    default-statement-timeout: 25000